import fs from 'fs';

let content = fs.readFileSync('src/pages/DashboardHr.tsx', 'utf-8');

const dict = {
  'Vaš dogodek': 'Vaš događaj',
  'Nimate še dogodka': 'Nemate još događaj',
  'Ustvarite svoj prvi dogodek za začetek zbiranja spominov.': 'Napravite svoj prvi događaj za početak skupljanja uspomena.',
  'Ustvari dogodek': 'Napravi događaj',
  'Tvoj dogodek': 'Tvoj događaj',
  'Dodaj nov dogodek': 'Dodaj novi događaj',
  'Trenutno preizkušate demo paket. Da bodo gostje lahko naložili več slik in dostopali do vseh funkcij, odklenite vaš dogodek.': 'Trenutno isprobavate demo paket. Da bi gosti mogli učitati više slika i pristupiti svim funkcijama, otključajte vaš događaj.',
  'Odkleni moj dogodek': 'Otključaj moj događaj',
  " Pregled dogodka": " Pregled događaja",
  'Upravljaj spomine s poslovnega dogodka.': 'Upravljajte uspomenama s poslovnog događaja.',
  'Vaša poroka': 'Vaše vjenčanje',
  'Upravljaj z vsemi spomini in nastavitvami s tvoje poroke.': 'Upravljaj sa svim uspomenama i postavkama sa svog vjenčanja.',
  'zabava': 'zabava',
  'Upravljaj spomine s te zabave.': 'Upravljaj uspomenama s ove zabave.',
  'Upravljaj spomine z rojstnega dne.': 'Upravljaj uspomenama s rođendana.',
  'Vaš rojstni dan': 'Vaš rođendan',
  'Vaša zabava': 'Vaša zabava',
  'Poslovni dogodek': 'Poslovni događaj',
  'Prenesi QR': 'Preuzmi QR',
  'Kopiraj link': 'Kopiraj link',
  'Izbriši': 'Obriši',
  'Nastavitve': 'Postavke',
  'Fotografije in videi': 'Fotografije i videi',
  'Ogled Live galerije': 'Prikaz Live galerije',
  'Prenesi vse slike (.zip)': 'Preuzmi sve slike (.zip)',
  'Načrtovanje prenašanja ...': 'Planiranje preuzimanja ...',
  'Nalaganje ...': 'Učitavanje ...',
  'Odkleni polno galerijo': 'Otključaj punu galeriju',
  'Slovensko': 'Hrvatski',
  'Prijava napaka': 'Prijavite pogrešku',
  'Vse fotografije in videi (': 'Sve fotografije i videi (',
  'Pritisni in drži za ogled videa': 'Pritisnite i držite za pregled videa',
  'Ni dodanih slik': 'Nema dodanih slika',
  'Gostje na vaš dogodek še niso dodali datotek.': 'Gosti još nisu dodali datoteke na vaš događaj.',
  'Spremeni paket': 'Promijeni paket',
  'Trenutni paket': 'Trenutni paket',
  'Zasebnost & varnost': 'Privatnost i sigurnost',
  'Zakleni dogodek': 'Zaključaj događaj',
  'Izbriši dogodek': 'Obriši događaj',
  "Izbris no mogoč, dokler dogodek še traja.": "Brisanje nije moguće dok događaj još traje.",
  'Uspešno shranjeno': 'Uspješno spremljeno',
  'Naziv dogodka': 'Naziv događaja',
  'Datum dogodka': 'Datum događaja',
  'Potrdi': 'Potvrdi',
  'Prekliči': 'Odustani',
  'Želite izbrisati ta dogodek? Tega dejanja ni mogoče razveljaviti in vse fotografije in videi bodo izbrisani!': 'Želite obrisati ovaj događaj? Ova akcija se ne može poništiti i sve fotografije i videozapisi bit će obrisani!',
  "Vaš dogodek še vedno traja, zato ga ni mogoče izbrisati.": "Vaš događaj još uvijek traje, stoga se ne može obrisati.",
  "Da": "Da",
  "Ne": "Ne",
  'Zapri zbiranje': 'Zatvori prikupljanje',
  "Prekini zbiranje slik na ta dogodek. QR koda bo postala neveljavna in povezava ne bo več delovala.": "Prekini prikupljanje slika na ovom događaju. QR kod će postati nevažeći i poveznica više neće raditi.",
  "Dovoli zbiranje": "Dopusti prikupljanje",
  "Galerija": "Galerija",
  "Za izbris vseh slik prosim izbrišite dogodek.": "Za brisanje svih slika molimo obrišite događaj.",
  "Ime dogodka (največ 30 znakov)": "Ime događaja (najviše 30 znakova)",
  "Osnovno": "Osnovno",
  "Partner 1": "Partner 1",
  "Partner 2": "Partner 2",
  "Sporočilo gostom": "Poruka gostima",
  "To sporočilo bo prikazano gostom, ko odprejo vašo galerijo.": "Ova poruka će se prikazati gostima kada otvore vašu galeriju.",
  "Vaš nakup je bil uspešen! Nalagamo podatke...": "Vaša kupnja je bila uspješna! Učitavamo podatke...",
  "Pregled dogodka": "Pregled događaja",
  "Paket:": "Paket:",
  "Gostje še spijo?": "Gosti još spavaju?",
  "Pošlji jim povezavo": "Pošalji im poveznicu",
  "Načrtuj Live galerijo": "Planiraj Live galeriju",
  "Galerija v živo": "Galerija uživo",
  "Videoposnetki (.mp4, .mov) in fotografije (.jpg, .png, .gif) do 50MB.": "Videozapisi (.mp4, .mov) i fotografije (.jpg, .png, .gif) do 50MB.",
  "Zaradi omejitev brskalnika priporočamo prenos videov in slik na računalnik z gumbom \"Prenesi vse (.zip)\".": "Zbog ograničenja preglednika preporučujemo preuzimanje videozapisa i slika na računalo pomoću gumba \"Preuzmi sve (.zip)\".",
  "Ustvarjam prenos, to lahko traja nekaj časa...": "Stvaram preuzimanje, to može potrajati...",
  "Ogled Live Galerije": "Prikaz Live Galerije",
  "Prostor za objavo galerije": "Prostor za objavu galerije",
  "Preklicano": "Otkazano",
  "Prekliči prenos": "Otkaži preuzimanje",
  "Odkrij": "Otkrij",
  "Zamenjaj": "Zamjeni",
  "Pripravite vse za dogodek": "Pripremite sve za događaj",
  "Datoteke pripravljene za prenos...": "Datoteke spremne za preuzimanje...",
  "Zbiram datoteke...": "Prikupljam datoteke...",
  "Datoteka preskočena (ne najdem URL-ja)": "Datoteka preskočena (ne mogu pronaći URL)",
  "Medija ni mogoče prenesti": "Medij se ne može preuzeti"
};

for (const [slo, hr] of Object.entries(dict)) {
  content = content.split(slo).join(hr);
}

fs.writeFileSync('src/pages/DashboardHr.tsx', content);

console.log("DashboardHr fine-tuned translation done");
